global using System;
global using System.IO;
global using System.Xml;
global using System.Linq;
global using System.Xml.Linq;
global using static System.Console;
global using System.Collections.Generic;
global using Re4ExeExtractor.Data.XML;
global using Re4ExeExtractor.Resources;
global using Re4ExeExtractor.Data.XML.ReadXML;
global using Re4ExeExtractor.Data.XML.WriteXML;
global using Re4ExeExtractor.Resources.Player;
global using Re4ExeExtractor.Resources.Weapon;
global using Re4ExeExtractor.Resources.Item.Stock;
global using Re4ExeExtractor.Resources.Item.Price;
global using Re4ExeExtractor.Resources.Item.Combine;
global using Re4ExeExtractor.Resources.Healing;