global using System;
global using System.IO;
global using System.Xml;
global using System.Linq;
global using System.Xml.Linq;
global using static System.Console;
global using System.Collections.Generic;
global using Re4ExeEditor.Data.XML;
global using Re4ExeEditor.Resources;
global using Re4ExeEditor.Data.XML.ReadXML;
global using Re4ExeEditor.Data.XML.WriteXML;
global using Re4ExeEditor.Resources.Player;
global using Re4ExeEditor.Resources.Weapon;
global using Re4ExeEditor.Resources.Item.Stock;
global using Re4ExeEditor.Resources.Item.Price;
global using Re4ExeEditor.Resources.Item.Stack;
global using Re4ExeEditor.Resources.Item.Combine;
global using Re4ExeEditor.Resources.Healing;